services:
  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: auth_db
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    networks:
      - auth-network
    volumes:
      - auth_db_data:/var/opt/mssql

  auth-service:
    build:
      context: ./AuthServiceEcoF
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      ConnectionStrings__DefaultConnection: "Server=auth-db,1433;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;Connection Timeout=30;"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      BCRYPT_WORK_FACTOR: ${BCRYPT_WORK_FACTOR}
    ports:
      - "8081:8081"
      - "8080:8080"
    depends_on:
      - auth-db
    networks:
      - auth-network
    restart: unless-stopped
    command: >
      sh -c "sleep 45 && dotnet AuthService.API.dll"

  vehicle-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vehicle_db
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    networks:
      - vehicle-network
    volumes:
      - vehicle_db_data:/var/opt/mssql
    restart: unless-stopped

  vehicle-service:
    build:
      context: ./VehicleServiceEcoF
      dockerfile: Dockerfile
    container_name: vehicle_service
    environment:
      ConnectionStrings__DefaultConnection: "Server=vehicle-db,1433;Database=${DB_NAME};User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;Connection Timeout=30;"
      ConnectionStrings__AuthService: "http://auth_service:8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8082"
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      VEHICLE_SERVICE_NAME: ${VEHICLE_SERVICE_NAME}
    ports:
      - "8082:8082"
    depends_on:
      - vehicle-db
    networks:
      - vehicle-network
    restart: unless-stopped

  api-gateway:
    build:
      context: ./ApiGatewayEcoF
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8085:8080"
    networks:
      - auth-network
      - vehicle-network
    depends_on:
      - auth-service
      - vehicle-service

networks:
  auth-network:
    driver: bridge
  vehicle-network:
    driver: bridge

volumes:
  auth_db_data:
  vehicle_db_data:
