services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8085:8080"
    networks:
      - auth-network
      - vehicle-network
    depends_on:
      - auth-service
      - vehicle-service

networks:
  auth-network:
    external: true
  vehicle-network:
    external: true
